"""Add additional columns to users table

Revision ID: d0036dc2aec1
Revises: ffdc0a98111c
Create Date: 2023-11-29 14:14:50.578504

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'd0036dc2aec1'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=SCHEMA) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.String(length=1500), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=1500), nullable=True))
        batch_op.add_column(sa.Column('portfolio_pic_url', sa.String(length=1500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=SCHEMA) as batch_op:
        batch_op.drop_column('portfolio_pic_url')
        batch_op.drop_column('profile_pic_url')
        batch_op.drop_column('bio')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
